trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: 'exelonacr.azurecr.io/exelon-checkin-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'AzureSubscription'
    appName: 'exelon-checkin-app'
    imageName: 'exelonacr.azurecr.io/exelon-checkin-app:$(Build.BuildId)'
